---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 37065.
--- DateTime: 2024/9/15 14:53
---

local M = UnLua.Class()

function InitDebug()
    package.cpath = package.cpath .. ';C:/Users/37065/AppData/Roaming/JetBrains/Rider2024.2/plugins/EmmyLua/debugger/emmy/windows/x64/?.dll'
    local dbg = require('emmy_core')
    dbg.tcpConnect('localhost', 9966)
end

local socket = require("socket")
function isPortInUse(port)
    local tcp = assert(socket.tcp())
    local result = tcp:bind("127.0.0.1", port)
    if result == nil then
        return true
    else
        tcp:close()
        return false
    end
end

-- 检查端口9966是否被占用
local port = 9966
if isPortInUse(port) then
    print("Port " .. port .. " is in use.")
    -- 尝试连接调试器， 连接失败打印日志
    local status, err = pcall(InitDebug)
    if not status then
        print("Connect to EmmyLua Debug failed: " .. err)
    else
        print("Connect to EmmyLua Debug success")
    end
else
    print("Port " .. port .. " is available.")
end

print("Hello UnLua Entry")

return M